# values.yaml
global:
  falconSecret:
    enabled: true
    secretName: "${FALCON_SECRET_NAME}"
  containerRegistry:
    configJSON: "${ENCODED_DOCKER_CONFIG}"

falcon-sensor:
  enabled: true
  node:
    image:
      repository: "${SENSOR_REGISTRY}"
      tag: "${SENSOR_IMAGE_TAG}"
    daemonset:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"

falcon-kac:
  enabled: true
  image:
    repository: "${KAC_REGISTRY}"
    tag: "${KAC_IMAGE_TAG}"

falcon-image-analyzer:
  enabled: true
  deployment:
    enabled: true
  image:
    repository: "${IAR_REGISTRY}"
    tag: "${IAR_IMAGE_TAG}"
  crowdstrikeConfig:
    clusterName: "${CLUSTER_NAME}"
    cid: "${FALCON_CID}"
