apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconDeployment
metadata:
  labels:
    crowdstrike.com/component: sample
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: falcondeployment-sample
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: falcon-deployment
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: falcon-deployment
spec:
  falcon_api:
    cloud_region: autodiscover
  falconSecret:
    enabled: true
    namespace: falcon-secret
    secretName: falcon-secrets
  deployAdmissionController: true
  deployNodeSensor: true
  deployImageAnalyzer: true
  deployContainerSensor: false
  falconNodeSensor:
    node:
      tolerations:
        - effect: NoSchedule
          operator: Exists
          key: CriticalAddonsOnly
      advanced:
        autoUpdate: normal
        updatePolicy: linux-prod
  falconImageAnalyzer: {}
  falconAdmission: {}
